title: My Coding Journey
author: Sumit Dutta
email: sumitdutta51103@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I started competitive programming 3 months ago. At that time I didn't knew much
  but I am learnig new concepts day after day. In this repository you can view my submissions
  of different sites.

# social links
github_username:  NormalBoii # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
